"""Helm wrappers."""

from __future__ import annotations

import atexit
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Optional

from idea4rc_capsule.config import Config
from idea4rc_capsule.logging import fatal, log
from idea4rc_capsule.shell import run, run_check_output


def resolve_companion_binary(name: str) -> Optional[str]:
    """Locate a sibling pipx-installed binary (e.g. helm post-renderer).

    Tries, in order:
      1. ``shutil.which(name)`` — honours PATH (interactive shells)
      2. Same dir as the running Python interpreter (pipx venv layout:
         ``~/.local/pipx/venvs/idea4rc-capsule/bin/{python,idea4rc-*}``)
      3. ``~/.local/bin/<name>`` symlink that pipx maintains for the user

    Returns the absolute path or None.
    """
    if Path(name).is_absolute():
        return name if os.access(name, os.X_OK) else None
    candidates: list[Path] = []
    p = shutil.which(name)
    if p:
        candidates.append(Path(p))
    candidates.append(Path(sys.executable).resolve().parent / name)
    candidates.append(Path.home() / ".local" / "bin" / name)
    for cand in candidates:
        if cand.is_file() and os.access(cand, os.X_OK):
            return str(cand.resolve())
    return None


# Shell launcher that strips PYTHON* env vars before exec'ing the
# real post-renderer. Required because some helm distributions (notably
# microk8s.helm, a snap binary) inject their own PYTHONPATH/PYTHONHOME
# pointing at the snap's python 3.8 paths. When our python 3.10 venv
# interpreter inherits that, its site-packages discovery breaks and
# `from idea4rc_capsule.helm_post_renderer import main` fails with
# ModuleNotFoundError. Sanitising at the launcher entry is the only
# place the cleanup can run, since helm controls the env between us and
# our Python interpreter.
_LAUNCHER_TEMPLATE = """#!/bin/sh
# Auto-generated by idea4rc_capsule.helm._stage_post_renderer_launcher.
# Snap-shipped helm (e.g. microk8s.helm) sets PYTHONPATH for child procs;
# unset it so our pipx venv's site-packages is discovered correctly.
unset PYTHONPATH PYTHONHOME PYTHONNOUSERSITE PYTHONSTARTUP
exec "{target}" "$@"
"""


def _stage_post_renderer_launcher(target_binary: str) -> str:
    """Materialise an env-sanitising shell wrapper around ``target_binary``.

    Returns the absolute path to the temp wrapper, registered for
    deletion at interpreter exit. Mode 0700 so other users on the host
    cannot read / replace it.
    """
    fd, path = tempfile.mkstemp(prefix="idea4rc-hpr-launcher-", suffix=".sh")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(_LAUNCHER_TEMPLATE.format(target=target_binary))
        os.chmod(path, 0o700)
    except Exception:
        try:
            os.unlink(path)
        except OSError:
            pass
        raise
    atexit.register(_remove_launcher, path)
    return path


def _remove_launcher(path: str) -> None:
    try:
        os.unlink(path)
    except OSError:
        pass


def _resolve_post_renderer(cfg: Config) -> tuple[Optional[str], dict[str, str]]:
    """Return (launcher_path, env_overrides) for helm --post-renderer.

    Returns (None, {}) when the post-renderer is disabled or unconfigured.
    The returned ``launcher_path`` is a shell wrapper that sanitises the
    Python env vars before exec'ing the real post-renderer binary; see
    ``_stage_post_renderer_launcher`` for the rationale.
    """
    hpr = cfg.helm_post_renderer
    if not hpr.enabled or not hpr.kinds_to_drop:
        return None, {}
    binary = resolve_companion_binary(hpr.binary)
    if not binary:
        fatal(f"[helm_post_renderer].binary not found or not executable: "
              f"{hpr.binary}. Reinstall the pipx package "
              f"(`pipx reinstall idea4rc-capsule`), or pin an absolute "
              f"path in capsule.toml.")
    launcher = _stage_post_renderer_launcher(binary)
    env = {"IDEA4RC_HPR_DROP_KINDS": ",".join(hpr.kinds_to_drop)}
    return launcher, env


class Helm:
    def __init__(self, cfg: Config, *, dry_run: bool = False) -> None:
        self.cfg = cfg
        self.dry_run = dry_run
        self.bin = cfg.k8s.helm_bin
        self.ns = cfg.k8s.namespace
        self.release = cfg.k8s.release_name

    def cmd(self, *args: str, ns: Optional[str] = None) -> list[str]:
        out = [self.bin]
        if ns is not None:
            out += ["-n", ns]
        out += list(args)
        return out

    def status(self, *, release: Optional[str] = None,
               ns: Optional[str] = None) -> bool:
        if self.dry_run:
            return True
        proc = run(self.cmd("status", release or self.release, ns=ns or self.ns),
                   check=False, capture=True, log_cmd=False)
        return proc.returncode == 0

    def uninstall(self, *, release: Optional[str] = None,
                  ns: Optional[str] = None, wait: bool = True) -> None:
        rel = release or self.release
        ns = ns or self.ns
        if not self.status(release=rel, ns=ns):
            log(f"Release '{rel}' not present in namespace '{ns}'.")
            return
        log(f"Uninstalling Helm release '{rel}'")
        args = ["uninstall", rel]
        if wait:
            args.append("--wait")
        run(self.cmd(*args, ns=ns), dry_run=self.dry_run, check=True)

    def list_all(self) -> list[dict[str, str]]:
        out = run_check_output(self.cmd("list", "-A", "-o", "json"),
                               dry_run=self.dry_run, check=False, log_cmd=False)
        if not out:
            return []
        import json
        try:
            return json.loads(out)
        except Exception:
            return []

    def assert_release_only_in_namespace(self, release: Optional[str] = None,
                                         ns: Optional[str] = None) -> None:
        rel = release or self.release
        ns = ns or self.ns
        if self.dry_run:
            return
        for entry in self.list_all():
            if entry.get("name") == rel and entry.get("namespace") not in (ns, None, ""):
                fatal(f"Helm release '{rel}' already exists in namespace "
                      f"'{entry['namespace']}'. Delete it first or change "
                      f"release_name.")

    def dependency_update(self, chart_dir: str) -> None:
        run(self.cmd("dependency", "update", chart_dir),
            dry_run=self.dry_run, check=True)

    def dependency_build(self, chart_dir: str) -> None:
        run(self.cmd("dependency", "build", chart_dir),
            dry_run=self.dry_run, check=True)

    def _post_renderer_args(self) -> tuple[list[str], dict[str, str]]:
        binary, env = _resolve_post_renderer(self.cfg)
        if not binary:
            return [], {}
        log(f"Helm post-renderer: {binary} "
            f"drop_kinds={self.cfg.helm_post_renderer.kinds_to_drop}")
        return ["--post-renderer", binary], env

    def install(self, *, set_values: dict[str, str],
                values_file: Optional[str] = None) -> None:
        args = ["install", self.release, self.cfg.k8s.chart_path,
                "-n", self.ns]
        pr_args, pr_env = self._post_renderer_args()
        args += pr_args
        for k, v in set_values.items():
            args += ["--set", f"{k}={v}"]
        if values_file:
            args += ["-f", values_file]
        run([self.bin, *args], dry_run=self.dry_run, check=True,
            env=pr_env or None)

    def upgrade_install(self, *, wait: bool = True,
                        timeout: Optional[str] = None,
                        values_file: Optional[str] = None) -> None:
        if self.cfg.k8s.force_recreate_only:
            fatal("force_recreate_only=true blocks Helm upgrade/install path. "
                  "Use install-script mode for recreate-only deployments.")
        # NOTE: --create-namespace is intentionally omitted when the
        # post-renderer is enabled; namespaces are pre-created by the
        # orchestrator and the post-renderer drops Namespace docs from
        # rendered output. Adding --create-namespace would still work but
        # is misleading: helm wouldn't actually create one (no Namespace
        # in the post-rendered manifests).
        args = ["upgrade", "--install", self.release, self.cfg.k8s.chart_path,
                "-n", self.ns]
        pr_args, pr_env = self._post_renderer_args()
        args += pr_args
        if not pr_args:
            args.append("--create-namespace")
        if wait:
            args.append("--wait")
        if timeout:
            args += ["--timeout", timeout]
        if values_file:
            args += ["-f", values_file]
        run([self.bin, *args], dry_run=self.dry_run, check=True,
            env=pr_env or None)

    def assert_release_present(self) -> None:
        if not self.status():
            fatal(f"Install finished but release '{self.release}' is not present "
                  f"in namespace '{self.ns}' (helm_bin={self.bin}).")
